<?php 
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/main/include/prolog_before.php'); 
include("bm.php");
$arResult = Array (
    '0' => Array (
        'LID' => 'ru',
        'NAME' => 'ITSfera Includer 2222',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'itsfera_includer3',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'ITSfera Includer',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '26',
                'CODE' => 'itsfera_includer_content',
                'NAME' => 'Слайдер',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/itsfera_includer/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '#SITE_DIR#/itsfera_includer/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/itsfera_includer/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                ),
                'SECTIONS' => Array (
                    '0' => Array (
                        'TIMESTAMP_X' => '16.01.2015 19:58:19',
                        'DATE_CREATE' => '16.01.2015 19:58:19',
                        'IBLOCK_SECTION_ID' => '',
                        'ACTIVE' => 'Y',
                        'GLOBAL_ACTIVE' => 'Y',
                        'SORT' => '500',
                        'NAME' => 'Демо 1',
                        'PICTURE' => '',
                        'LEFT_MARGIN' => '1',
                        'RIGHT_MARGIN' => '2',
                        'DEPTH_LEVEL' => '1',
                        'DESCRIPTION' => '',
                        'DESCRIPTION_TYPE' => 'text',
                        'SEARCHABLE_CONTENT' => 'ДЕМО 1
',
                        'CODE' => 'demo-1',
                        'XML_ID' => '',
                        'DETAIL_PICTURE' => '',
                        'EXTERNAL_ID' => '',
                        'ELEMENTS' => Array (
                            '0' => Array (
                                'CODE' => 'poezda',
                                'EXTERNAL_ID' => '9',
                                'NAME' => 'Поезда',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti.',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '187',
                                    'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '768',
                                    'WIDTH' => '1024',
                                    'FILE_SIZE' => '472843',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/ad7',
                                    'FILE_NAME' => '9.jpg',
                                    'ORIGINAL_NAME' => '9.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/ad7/9.jpg',
                                    'NEW_SRC' => '187.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'DATE_CREATE' => '16.01.2015 19:58:19',
                                'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                'TAGS' => '',
                            ),
                            '1' => Array (
                                'CODE' => 'ulitka',
                                'EXTERNAL_ID' => '10',
                                'NAME' => 'Улитка',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '188',
                                    'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1365',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '200126',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/586',
                                    'FILE_NAME' => '10.jpg',
                                    'ORIGINAL_NAME' => '10.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/586/10.jpg',
                                    'NEW_SRC' => '188.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'DATE_CREATE' => '16.01.2015 19:58:19',
                                'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                'TAGS' => '',
                            ),
                            '2' => Array (
                                'CODE' => 'tsvetok',
                                'EXTERNAL_ID' => '11',
                                'NAME' => 'Цветок',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '189',
                                    'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1441',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '2039798',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/adf',
                                    'FILE_NAME' => '11.jpg',
                                    'ORIGINAL_NAME' => '11.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/adf/11.jpg',
                                    'NEW_SRC' => '189.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'DATE_CREATE' => '16.01.2015 19:58:19',
                                'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                'TAGS' => '',
                            ),
                        ),
                    ),
                    '1' => Array (
                        'TIMESTAMP_X' => '16.01.2015 19:58:19',
                        'DATE_CREATE' => '16.01.2015 19:58:19',
                        'IBLOCK_SECTION_ID' => '',
                        'ACTIVE' => 'Y',
                        'GLOBAL_ACTIVE' => 'Y',
                        'SORT' => '500',
                        'NAME' => 'Демо 2',
                        'PICTURE' => '',
                        'LEFT_MARGIN' => '3',
                        'RIGHT_MARGIN' => '4',
                        'DEPTH_LEVEL' => '1',
                        'DESCRIPTION' => '',
                        'DESCRIPTION_TYPE' => 'text',
                        'SEARCHABLE_CONTENT' => 'ДЕМО 2
',
                        'CODE' => 'demo-2',
                        'XML_ID' => '',
                        'DETAIL_PICTURE' => '',
                        'EXTERNAL_ID' => '',
                        'ELEMENTS' => Array (
                            '0' => Array (
                                'CODE' => 'ptitsa',
                                'EXTERNAL_ID' => '12',
                                'NAME' => 'Птица',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '190',
                                    'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1314',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '926226',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/f6e',
                                    'FILE_NAME' => '12.jpg',
                                    'ORIGINAL_NAME' => '12.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/f6e/12.jpg',
                                    'NEW_SRC' => '190.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'DATE_CREATE' => '16.01.2015 19:58:19',
                                'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                'TAGS' => '',
                            ),
                            '1' => Array (
                                'CODE' => 'most',
                                'EXTERNAL_ID' => '13',
                                'NAME' => 'Мост',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti.',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '191',
                                    'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1348',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '850725',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/2a6',
                                    'FILE_NAME' => '13.jpg',
                                    'ORIGINAL_NAME' => '13.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/2a6/13.jpg',
                                    'NEW_SRC' => '191.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'DATE_CREATE' => '16.01.2015 19:58:19',
                                'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                'TAGS' => '',
                            ),
                            '2' => Array (
                                'CODE' => 'utro',
                                'EXTERNAL_ID' => '14',
                                'NAME' => 'Утро',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, &quot;consectetur&quot; adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '192',
                                    'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1361',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '923891',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/ddc',
                                    'FILE_NAME' => '14.jpg',
                                    'ORIGINAL_NAME' => '14.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/ddc/14.jpg',
                                    'NEW_SRC' => '192.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'DATE_CREATE' => '16.01.2015 19:58:19',
                                'TIMESTAMP_X' => '17.01.2015 13:42:29',
                                'TAGS' => '',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);
$bm = new BitrixMigration(__FILE__);
$bm->sStoreFilesDir = '/bm_files/';
$bm->uploadArray($arResult);
?>